memereview/urls.py
# redirect the main view to the app
from django.views.generic import RedirectView
# Use include() to add URLS from the catalog application
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    # redirect the main view to the app
    path('', RedirectView.as_view(url='/reviews/', permanent=True)),
    # redirect reviews to the app
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
"""
This file was created
"""
from django.urls import path
from . import views

urlpatterns = [
    path("", views.MemeReviews.as_view(), name="meme_review_view"),
    path("<int:pk>/", views.MemeDetail.as_view(), name="meme-detail"),
    path("<int:id>/<slug:slug>/", views.MemeDetail.as_view(),
         name="meme-detail"),
]

reviews/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


# Create your models here.
class Image(models.Model):
    imageURL = models.URLField()

    def __str__(self):
        return self.imageURL


class Meme(models.Model):
    mainImage = models.ForeignKey('Image', on_delete=models.SET_NULL,
                                  null=True,
                                  related_name='mainImage')
    relatedImages = models.ManyToManyField('Image',
                                           related_name='relatedImages')
    reviews = models.ManyToManyField('Review')
    description = models.CharField(max_length=1000)
    title = models.CharField(max_length=300)
    dateCreated = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=300)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        return the url to access this particular post
        """
        return reverse('meme-detail', args=[self.id, slugify(self.title)])


class Review(models.Model):
    textReview = models.CharField(max_length=300)
    titleReview = models.CharField(max_length=100)
    ratingReview = models.IntegerField()

    def __str__(self):
        return self.titleReview

reviews/forms.py
from django import forms


class CreateReview(forms.Form):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'rows': '3'}))
    rating = forms.IntegerField(max_value=10, min_value=0)

reviews/views.py
from django.shortcuts import render
from django.views import generic, View
from .models import Image, Meme, Review
from .forms import CreateReview
from django.views.generic.edit import SingleObjectMixin, FormView
# from django.utils import slugify
from django.urls import reverse


# generic.ListView automatically gets the "context" the context is the data
# passed to the template like a dictionary {memes: meme} in this case
# all the memes
class MemeReviews(generic.ListView):
    model = Meme
    context_object_name = "meme_list"
    template_name = "index.html"
    paginate_by = 3
    ordering = ['-dateCreated']


# to have the meme review form in MemeDetailview we seperate the 2 reviews
# into MemeDisplay and MemeReviewFormView using mixins
class MemeDisplay(generic.DetailView):
    model = Meme

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # yes i know this shouldnt be done
        context['relatedMemes'] = Meme.objects.all()[:5]
        context['form'] = CreateReview()
        return context


class MemeReviewFormView(SingleObjectMixin, FormView):
    """
    MemeReviewFormView is a simple FormView, but we have to bring in
    SingleObjectMixin so we can find the meme we’re talking about, and we
    have to remember to set template_name to ensure that form errors will
    render the same template as MemeDisplay is using on GET
    """
    template_name = "reviews/meme_detail.html"
    form_class = CreateReview
    model = Meme

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        print("Meme name: " + str(self.object.title))
        return reverse('meme-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        reviewMo = Review(textReview=form.cleaned_data['message'],
                          titleReview="temp",
                          ratingReview=form.cleaned_data['rating'])
        reviewMo.save()
        self.object.reviews.add(reviewMo)
        return super().form_valid(form)


class MemeDetail(View):

    def get(self, request, *args, **kwargs):
        view = MemeDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = MemeReviewFormView.as_view()
        return view(request, *args, **kwargs)

reviews/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}<title>Clean Blog</title>{% endblock %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Theme CSS -->
    <!--
    {% load static %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    -->

    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'css/3-col-portfolio.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>

    {% block navigationbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/reviews">MEME ReViEWw</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/reviews">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">FrOG TeMPle</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">MoRe MeMEEs</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock navigationbar %}

    {% block content %}
    {% endblock content %}


    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">REspact wamen</p>
      </div>
    </footer>


    <!-- Boostrap javascript and plugins -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>

</html>

reviews/templates/index.html
{% extends "base_generic.html" %}

{% block title %} <title> Contacto </title> {% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <h1 class="my-4">HeRe tHe MEMEs
    <small>Secondary Text</small>
  </h1>

  {% if meme_list %}
  <div class="row">
    {% for meme in meme_list %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="{{meme.get_absolute_url}}"><img class="card-img-top" src="{{meme.mainImage}}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="{{meme.get_absolute_url}}">{{meme.title}}</a>
          </h4>
          <p class="card-text">{{meme.description}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}
  <!-- /.row -->

  <!-- Pagination
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">1</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#">3</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
-->

</div>
<!-- /.container -->
{% endblock content %}

reviews/templates/reviews/meme_detail.html
{% extends "base_generic.html" %}

{% block title %} <title> Contacto </title> {% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <h1 class="my-4">{{meme.title}}
    <small>a meme review</small>
  </h1>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <img class="img-fluid" src="{{meme.mainImage}}" alt="">
    </div>

    <div class="col-md-4">
      <h3 class="my-3">{{meme.title}}</h3>
      <p>{{meme.description}}</p>
    </div>

  </div>
  <!-- /.row -->

  <!-- comment section -->
  <div class="row">
    <!-- Post Content Column -->
    <div class="col-lg-8">
      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">Leave a Review:</h5>
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
          <!-- this is an example form
          <form>
            <div class="form-group">
              <p>
                <label for="id_message">Message:</label>
                <textarea name="message" cols="40" rows="3" class="form-control" required id="id_message"> </textarea>
              </p>
              <p>
                <label for="id_rating">Rating:</label>
                <input type="number" name="rating" min="0" max="10" required id="id_rating" />
              </p>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        -->
        </div>
      </div>

      <!-- Single Comment -->
      {% if meme.reviews.all %}
      {% for review in meme.reviews.all %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">Rating: {{review.ratingReview}}/10</h5>
          {{review.textReview}}
        </div>
      </div>
      <hr>
      {% endfor %}
      {% endif %}

    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

  <!-- Related Projects Row -->
  <h3 class="my-4">OtHeR MEmeS</h3>

  <div class="row">


    {% if relatedMemes %}
    {% for imageMeme in relatedMemes %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="{{imageMeme.get_absolute_url}}"><img class="card-img-top" src="{{imageMeme.mainImage}}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="{{imageMeme.get_absolute_url}}">{{imageMeme.title}}</a>
          </h4>
          <p class="card-text">{{imageMeme.description}}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}

    <!--
    {% if relatedMemes %}
    {% for imageMeme in relatedMemes %}
    <div class="col-md-3 col-sm-6 mb-4">
      <a href="{{imageMeme.get_absolute_url}}">
        <img class="img-fluid" src="{{imageMeme.mainImage}}" alt="">
      </a>
    </div>
    {% endfor %}
    {% endif %}
  -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

{% endblock content %}